### ISSUE TITLE
[BUG] /find redirects to http for secure connections

### ISSUE THREAD

**Issue by line-o** [eXist-db/public-repo#74]
```
> GET /exist/apps/public-repo/find?name=http%3A%2F%2Fexistsolutions.com%2Fns%2Fjwt&processor=6.0.0&semver=2.0.0 HTTP/1.1
> Host: exist-db.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Wed, 16 Feb 2022 14:07:30 GMT
< Server: Jetty(9.4.44.v20210927)
< X-XQuery-Cached: true
< Location: http://exist-db.org/exist/apps/public-repo/public/jwt-2.0.0.xar
< Content-Length: 0
```

**Comment by joewiz** [comment]
We need a method - ideally generalized but at worst specific to exist-db.org - to determine the scheme. If `request:get-scheme()` is reliable, then we could use this in constructing an absolute URL for the `response:redirect()` function responsible for the 302 here. This may not be a generalized solution, though, since proxies may forward traffic to eXist over HTTP - in which case how could eXist know whether the original request was HTTPS or not?

**Comment by line-o** [comment]
When a request is redirected the header `X-Forwarded-For` is set. That __can__ be used to determine a different absolute URL.
But it is also a very different use case that is currently unsupported anyway. First immediate goal is to enable loading of dependencies from a public-repo instance over HTTPS.

**Comment by line-o** [comment]
It turns out that this is already fixed in master. So existdb.org just needs updating to v2.1.0 once it is released.
/cc @joewiz

**Comment by line-o** [comment]
#48 describe almost the same problem. So it was either reintroduced with 1.1.0 or 2.0.0 or it was never fixed for non-proxied set-ups.

**Comment by line-o** [comment]
I would leave this open until it is fixed on exist-db.org

**Comment by joewiz** [comment]
Ah, yes, that's prudent!
